--ASIGNANDO PRIVILEGIOS
--USUARIO 1 DUEÑO
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER BDY1102_P9_1 IDENTIFIED BY "BDY1102_P9.practica"
DEFAULT TABLESPACE "USERS" --ESPECIFICA EL TABLESPACE POR DEFECTO EN QUE LOS OBJETOS CREADOS 
                            --POR EL USUARIO QUEDARAN ALMACENADOS (LAS TABLAS QUE SE PUEDEN GUARDAR EN EL USUARIO CREADO)
TEMPORARY TABLESPACE "TEMP" --ESPECIFICA EL TABLESPACE TEMPORAL DEL USUARIO 
QUOTA UNLIMITED ON USERS; --ESPECIFICA LA CANTIDAD MAXIMA DE ESPACIO ASIGNADO AL USUARIO PARA ALMACENAR SUS OBJETOS.
GRANT CREATE SESSION TO BDY1102_P9_1; --LINEA PARA DAR PERMISO Y PODER CREAR SESSION 


--USUARIO 2 

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER BDY1102_P9_2 IDENTIFIED BY "BDY1102_P9.practica"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P9_2;
GRANT CREATE TRIGGER TO BDY1102_P9_2;
GRANT CREATE MATERIALIZED VIEW TO BDY1102_P9_2;
GRANT CREATE PROCEDURE TO BDY1102_P9_2;
GRANT CREATE VIEW TO BDY1102_P9_2;

--USUARIO 3 

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER BDY1102_P9_3 IDENTIFIED BY "BDY1102_P9.practica"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P9_3 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P9_3;
GRANT "RESOURCE" TO BDY1102_P9_3;
ALTER USER BDY1102_P9_3 DEFAULT ROLE "RESOURCE";
GRANT CREATE VIEW TO BDY1102_P9_3;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER BDY1102_P9_4 IDENTIFIED BY "BDY1102_P9.practica"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P9_4 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BDY1102_P9_4;
GRANT "RESOURCE" TO BDY1102_P9_4;
ALTER USER BDY1102_P9_4 DEFAULT ROLE "RESOURCE";
GRANT CREATE VIEW TO BDY1102_P9_4;


--GRANT (DML) DELETE- INSERT - UPDATE - SELECT
--GRANT CREATE (VISTAS - PROCEDIMIENTOS - TRIGGER)

DROP USER BDY1102_P9_1